// Generated by tools/build_audio.js. Small manifest only; audio payloads are lazy chunks.
(function (global) {
  "use strict";
  var Voxel = global.Voxel = global.Voxel || {};
  var doc = global.document;
  var current = doc && doc.currentScript;
  if ((!current || !current.src) && doc && doc.scripts) {
    for (var i = doc.scripts.length - 1; i >= 0; i--) {
      if (/(^|\/)assets\.js(?:[?#]|$)/.test(doc.scripts[i].src || "")) { current = doc.scripts[i]; break; }
    }
  }
  var baseUrl = "js/";
  if (current && current.src) {
    try { baseUrl = new URL(".", current.src).href; }
    catch (error) { baseUrl = current.src.slice(0, current.src.lastIndexOf("/") + 1); }
  }
  var audio = {};
  var loadedChunks = {};
  var chunks = {
    "sfx": {
      "id": "sfx",
      "file": "assets-sfx.js",
      "hash": "90217c45c186ac540939d10a7c6dc203b525177a9c2abcae25111f0b1e83ae10",
      "payloadHash": "22e3609d257ff6bfb697041c9ce70f0831712798d039baebdee18e396e0b6904",
      "version": "sha256-90217c45c186ac540939d10a7c6dc203b525177a9c2abcae25111f0b1e83ae10",
      "names": [
        "cat_0",
        "cat_1",
        "cat_2",
        "cat_3",
        "cat_hurt",
        "dig_0",
        "dig_1",
        "dig_2",
        "dig_glass_0",
        "dig_glass_1",
        "dig_glass_2",
        "dig_wood_0",
        "dig_wood_1",
        "dig_wood_2",
        "land_0",
        "land_1",
        "land_2",
        "scream_0",
        "scream_1",
        "scream_2",
        "sheep_0",
        "sheep_1",
        "sheep_2",
        "sheep_hurt",
        "splash_0",
        "splash_step_0",
        "splash_step_1",
        "step_dirt_0",
        "step_dirt_1",
        "step_grass_0",
        "step_grass_1",
        "step_grass_2",
        "step_leaves_0",
        "step_leaves_1",
        "step_sand_0",
        "step_sand_1",
        "step_snow_0",
        "step_snow_1",
        "step_snow_2",
        "step_stone_0",
        "step_stone_1",
        "step_stone_2",
        "step_wood_0",
        "step_wood_1",
        "step_wood_2",
        "step_wool_0",
        "step_wool_1",
        "step_wool_2",
        "ui_0",
        "zombie_0"
      ],
      "count": 50,
      "bytes": 464364
    },
    "music-day": {
      "id": "music-day",
      "file": "assets-music-day.js",
      "hash": "b1beac513fb618470ce56e008e5b3680daf274a61120ee1b3c44748926234060",
      "payloadHash": "a96839c7960829e3b92ec4535bd35effcae58dbc285a34f885e9ced376fbfe6d",
      "version": "sha256-b1beac513fb618470ce56e008e5b3680daf274a61120ee1b3c44748926234060",
      "names": [
        "music_day"
      ],
      "count": 1,
      "bytes": 702671
    },
    "music-night": {
      "id": "music-night",
      "file": "assets-music-night.js",
      "hash": "37df65c839be7ad91fd98685759413ec686fe56b7189bd813585f6fbcb44d356",
      "payloadHash": "2b75a235270d302b5a304ac9ee4078924bb1c1ee6b980e09506ea59455457c37",
      "version": "sha256-37df65c839be7ad91fd98685759413ec686fe56b7189bd813585f6fbcb44d356",
      "names": [
        "music_night"
      ],
      "count": 1,
      "bytes": 865043
    }
  };
  Object.keys(chunks).forEach(function (id) {
    var chunk = chunks[id];
    var href;
    try { href = new URL(chunk.file, baseUrl).href; }
    catch (error) { href = baseUrl + chunk.file; }
    chunk.url = href + "?v=" + chunk.hash;
  });
  function registerAudioChunk(id, payloadHash, entries) {
    var chunk = chunks[id];
    if (!chunk || chunk.payloadHash !== payloadHash || !entries || typeof entries !== "object") {
      throw new Error("Invalid Voxel audio chunk: " + id);
    }
    var names = Object.keys(entries).sort();
    var expected = chunk.names.slice().sort();
    var audioPrefix = "data:" + "audio/mpeg;base64,";
    if (names.length !== expected.length) throw new Error("Incomplete Voxel audio chunk: " + id);
    for (var i = 0; i < expected.length; i++) {
      if (names[i] !== expected[i] || typeof entries[names[i]] !== "string" ||
          entries[names[i]].indexOf(audioPrefix) !== 0) {
        throw new Error("Invalid Voxel audio entry: " + id + "/" + expected[i]);
      }
    }
    names.forEach(function (name) { audio[name] = entries[name]; });
    loadedChunks[id] = chunk.hash;
    return names.length;
  }
  Voxel.Assets = {
    schemaVersion: 2,
    baseUrl: baseUrl,
    audio: audio,
    audioToChunk: {
      "cat_0": "sfx",
      "cat_1": "sfx",
      "cat_2": "sfx",
      "cat_3": "sfx",
      "cat_hurt": "sfx",
      "dig_0": "sfx",
      "dig_1": "sfx",
      "dig_2": "sfx",
      "dig_glass_0": "sfx",
      "dig_glass_1": "sfx",
      "dig_glass_2": "sfx",
      "dig_wood_0": "sfx",
      "dig_wood_1": "sfx",
      "dig_wood_2": "sfx",
      "land_0": "sfx",
      "land_1": "sfx",
      "land_2": "sfx",
      "scream_0": "sfx",
      "scream_1": "sfx",
      "scream_2": "sfx",
      "sheep_0": "sfx",
      "sheep_1": "sfx",
      "sheep_2": "sfx",
      "sheep_hurt": "sfx",
      "splash_0": "sfx",
      "splash_step_0": "sfx",
      "splash_step_1": "sfx",
      "step_dirt_0": "sfx",
      "step_dirt_1": "sfx",
      "step_grass_0": "sfx",
      "step_grass_1": "sfx",
      "step_grass_2": "sfx",
      "step_leaves_0": "sfx",
      "step_leaves_1": "sfx",
      "step_sand_0": "sfx",
      "step_sand_1": "sfx",
      "step_snow_0": "sfx",
      "step_snow_1": "sfx",
      "step_snow_2": "sfx",
      "step_stone_0": "sfx",
      "step_stone_1": "sfx",
      "step_stone_2": "sfx",
      "step_wood_0": "sfx",
      "step_wood_1": "sfx",
      "step_wood_2": "sfx",
      "step_wool_0": "sfx",
      "step_wool_1": "sfx",
      "step_wool_2": "sfx",
      "ui_0": "sfx",
      "zombie_0": "sfx",
      "music_day": "music-day",
      "music_night": "music-night"
    },
    chunks: chunks,
    loadedChunks: loadedChunks,
    registerAudioChunk: registerAudioChunk,
    isChunkLoaded: function (id) { return loadedChunks[id] === (chunks[id] && chunks[id].hash); },
    credits: [
      {
        "files": "step_grass_*, step_snow_*, step_stone_*, step_wood_*, step_wool_*, dig_*, dig_wood_*, dig_glass_*, land_*, ui_*",
        "source": "Kenney \"Impact Sounds\" (kenney.nl)",
        "license": "CC0 1.0"
      },
      {
        "files": "step_dirt_0",
        "source": "Kenney \"Impact Sounds\" (kenney.nl), pitch-shifted",
        "license": "CC0 1.0"
      },
      {
        "files": "step_dirt_1, step_leaves_0, step_leaves_1",
        "source": "\"Different steps on wood, stone, leaves, gravel and mud\" by kdd (opengameart.org)",
        "license": "CC0 1.0"
      },
      {
        "files": "step_sand_0, step_sand_1, splash_step_0, splash_step_1, sheep_0, sheep_1, sheep_2, sheep_hurt, splash_0",
        "source": "Yo Frankie! game assets via opengameart.org (sfx_step_*/sheep*/watersplash)",
        "license": "CC-BY 3.0 (Blender Foundation / Apricot project)"
      },
      {
        "files": "zombie_0",
        "source": "\"Zombie Sound\" (opengameart.org/content/zombie-sound)",
        "license": "CC0 1.0"
      },
      {
        "files": "scream_0",
        "source": "\"Girly Scream\" by Ferk, performed by Mariel Carmona Varo (opengameart.org/content/girly-scream)",
        "license": "CC0 1.0"
      },
      {
        "files": "scream_1",
        "source": "\"Girl Scream\" by tcrocker68 via congusbongus's \"Female screams\" pack (freesound.org/s/235592, opengameart.org/content/female-screams)",
        "license": "CC0 1.0"
      },
      {
        "files": "scream_2",
        "source": "\"human male scream multi\" by JohnsonBrandEditing, extracted in congusbongus's \"Aargh! (male screams)\" pack (freesound.org/s/173944, opengameart.org/content/aargh-male-screams)",
        "license": "CC0 1.0"
      },
      {
        "files": "cat_0",
        "source": "\"cat meow\" by tuberatanka (freesound.org/s/110011)",
        "license": "CC0 1.0"
      },
      {
        "files": "cat_1, cat_hurt (pitch-shifted)",
        "source": "\"cat meow short\" by skymary (freesound.org/s/412017)",
        "license": "CC0 1.0"
      },
      {
        "files": "cat_2 (pitch-shifted)",
        "source": "\"meow51252153\" by suicdxsaturday (freesound.org/s/698633)",
        "license": "CC0 1.0"
      },
      {
        "files": "cat_3",
        "source": "\"meow9.wav\" by freemaster2 (freesound.org/s/66518)",
        "license": "CC0 1.0"
      },
      {
        "files": "music_day",
        "source": "\"Calm Ambient 3 - Lifewave 2k\" by The Cynic Project / Pixelsphere (opengameart.org)",
        "license": "CC0 1.0"
      },
      {
        "files": "music_night",
        "source": "\"Calm Piano 1 - Vaporware\" by The Cynic Project / Pixelsphere (opengameart.org)",
        "license": "CC0 1.0"
      }
    ]
  };
})(window);
