#!/usr/bin/env node
// Build the deterministic, lazy audio manifest and its three script chunks.
// Usage:
//   node tools/build_audio.js          write generated files
//   node tools/build_audio.js --check  verify generated files are current
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'assets_src', 'audio');
const JS_DIR = path.join(ROOT, 'js');

const CHUNK_SPECS = [
  { id: 'sfx', file: 'assets-sfx.js', select: name => !name.startsWith('music_') },
  { id: 'music-day', file: 'assets-music-day.js', select: name => name === 'music_day' },
  { id: 'music-night', file: 'assets-music-night.js', select: name => name === 'music_night' }
];

// Source credits are kept in the small manifest so they are available before
// any audio payload is requested.
const CREDITS = [
  { files: 'step_grass_*, step_snow_*, step_stone_*, step_wood_*, step_wool_*, dig_*, dig_wood_*, dig_glass_*, land_*, ui_*',
    source: 'Kenney "Impact Sounds" (kenney.nl)', license: 'CC0 1.0' },
  { files: 'step_dirt_0', source: 'Kenney "Impact Sounds" (kenney.nl), pitch-shifted', license: 'CC0 1.0' },
  { files: 'step_dirt_1, step_leaves_0, step_leaves_1',
    source: '"Different steps on wood, stone, leaves, gravel and mud" by kdd (opengameart.org)', license: 'CC0 1.0' },
  { files: 'step_sand_0, step_sand_1, splash_step_0, splash_step_1, sheep_0, sheep_1, sheep_2, sheep_hurt, splash_0',
    source: 'Yo Frankie! game assets via opengameart.org (sfx_step_*/sheep*/watersplash)', license: 'CC-BY 3.0 (Blender Foundation / Apricot project)' },
  { files: 'zombie_0', source: '"Zombie Sound" (opengameart.org/content/zombie-sound)', license: 'CC0 1.0' },
  { files: 'music_day', source: '"Calm Ambient 3 - Lifewave 2k" by The Cynic Project / Pixelsphere (opengameart.org)', license: 'CC0 1.0' },
  { files: 'music_night', source: '"Calm Piano 1 - Vaporware" by The Cynic Project / Pixelsphere (opengameart.org)', license: 'CC0 1.0' }
];

function readSources() {
  if (!fs.existsSync(SRC)) throw new Error('找不到 ' + SRC + '，请先运行 tools/process_audio.sh');
  const files = fs.readdirSync(SRC).filter(file => file.endsWith('.mp3')).sort();
  if (!files.length) throw new Error('assets_src/audio 为空');
  return files.map(file => ({
    file,
    name: file.replace(/\.mp3$/, ''),
    buffer: fs.readFileSync(path.join(SRC, file))
  }));
}

function chunkHash(entries) {
  const hash = crypto.createHash('sha256');
  entries.forEach(entry => {
    hash.update(entry.name, 'utf8');
    hash.update(Buffer.from([0]));
    hash.update(entry.buffer);
  });
  return hash.digest('hex');
}

function makeChunk(spec, entries, payloadHash) {
  const audioEntries = entries.map(entry =>
    '    ' + JSON.stringify(entry.name) + ': ' +
      JSON.stringify('data:audio/mpeg;base64,' + entry.buffer.toString('base64'))
  ).join(',\n');
  return [
    '// Generated by tools/build_audio.js from assets_src/audio. Do not edit.',
    '(function (global) {',
    '  "use strict";',
    '  var assets = global.Voxel && global.Voxel.Assets;',
    '  if (!assets || typeof assets.registerAudioChunk !== "function") {',
    '    throw new Error("Voxel audio manifest must load before ' + spec.file + '");',
    '  }',
    '  assets.registerAudioChunk(' + JSON.stringify(spec.id) + ', ' + JSON.stringify(payloadHash) + ', {',
    audioEntries,
    '  });',
    '})(window);',
    ''
  ].join('\n');
}

function makeManifest(chunks) {
  const metadata = {};
  const audioToChunk = {};
  chunks.forEach(chunk => {
    metadata[chunk.id] = {
      id: chunk.id,
      file: chunk.file,
      hash: chunk.fileHash,
      payloadHash: chunk.payloadHash,
      version: 'sha256-' + chunk.fileHash,
      names: chunk.entries.map(entry => entry.name),
      count: chunk.entries.length,
      bytes: chunk.entries.reduce((sum, entry) => sum + entry.buffer.length, 0)
    };
    chunk.entries.forEach(entry => { audioToChunk[entry.name] = chunk.id; });
  });

  return [
    '// Generated by tools/build_audio.js. Small manifest only; audio payloads are lazy chunks.',
    '(function (global) {',
    '  "use strict";',
    '  var Voxel = global.Voxel = global.Voxel || {};',
    '  var doc = global.document;',
    '  var current = doc && doc.currentScript;',
    '  if ((!current || !current.src) && doc && doc.scripts) {',
    '    for (var i = doc.scripts.length - 1; i >= 0; i--) {',
    '      if (/(^|\\/)assets\\.js(?:[?#]|$)/.test(doc.scripts[i].src || "")) { current = doc.scripts[i]; break; }',
    '    }',
    '  }',
    '  var baseUrl = "js/";',
    '  if (current && current.src) {',
    '    try { baseUrl = new URL(".", current.src).href; }',
    '    catch (error) { baseUrl = current.src.slice(0, current.src.lastIndexOf("/") + 1); }',
    '  }',
    '  var audio = {};',
    '  var loadedChunks = {};',
    '  var chunks = ' + JSON.stringify(metadata, null, 2).split('\n').join('\n  ') + ';',
    '  Object.keys(chunks).forEach(function (id) {',
    '    var chunk = chunks[id];',
    '    var href;',
    '    try { href = new URL(chunk.file, baseUrl).href; }',
    '    catch (error) { href = baseUrl + chunk.file; }',
    '    chunk.url = href + "?v=" + chunk.hash;',
    '  });',
    '  function registerAudioChunk(id, payloadHash, entries) {',
    '    var chunk = chunks[id];',
    '    if (!chunk || chunk.payloadHash !== payloadHash || !entries || typeof entries !== "object") {',
    '      throw new Error("Invalid Voxel audio chunk: " + id);',
    '    }',
    '    var names = Object.keys(entries).sort();',
    '    var expected = chunk.names.slice().sort();',
    '    var audioPrefix = "data:" + "audio/mpeg;base64,";',
    '    if (names.length !== expected.length) throw new Error("Incomplete Voxel audio chunk: " + id);',
    '    for (var i = 0; i < expected.length; i++) {',
    '      if (names[i] !== expected[i] || typeof entries[names[i]] !== "string" ||',
    '          entries[names[i]].indexOf(audioPrefix) !== 0) {',
    '        throw new Error("Invalid Voxel audio entry: " + id + "/" + expected[i]);',
    '      }',
    '    }',
    '    names.forEach(function (name) { audio[name] = entries[name]; });',
    '    loadedChunks[id] = chunk.hash;',
    '    return names.length;',
    '  }',
    '  Voxel.Assets = {',
    '    schemaVersion: 2,',
    '    baseUrl: baseUrl,',
    '    audio: audio,',
    '    audioToChunk: ' + JSON.stringify(audioToChunk, null, 2).split('\n').join('\n    ') + ',',
    '    chunks: chunks,',
    '    loadedChunks: loadedChunks,',
    '    registerAudioChunk: registerAudioChunk,',
    '    isChunkLoaded: function (id) { return loadedChunks[id] === (chunks[id] && chunks[id].hash); },',
    '    credits: ' + JSON.stringify(CREDITS, null, 2).split('\n').join('\n    '),
    '  };',
    '})(window);',
    ''
  ].join('\n');
}

function generatedFiles() {
  const sources = readSources();
  const chunks = CHUNK_SPECS.map(spec => {
    const entries = sources.filter(entry => spec.select(entry.name));
    const payloadHash = chunkHash(entries);
    const text = makeChunk(spec, entries, payloadHash);
    const fileHash = crypto.createHash('sha256').update(text, 'utf8').digest('hex');
    return { ...spec, entries, payloadHash, fileHash, text };
  });

  const assigned = new Set(chunks.flatMap(chunk => chunk.entries.map(entry => entry.name)));
  if (assigned.size !== sources.length || chunks.some(chunk => !chunk.entries.length)) {
    throw new Error('音频分块必须完整且互斥');
  }
  if (chunks[0].entries.length !== 42 || chunks[1].entries.length !== 1 || chunks[2].entries.length !== 1) {
    throw new Error('音频清单必须为 42 个 SFX、1 首白昼音乐、1 首夜晚音乐');
  }

  const outputs = new Map();
  outputs.set(path.join(JS_DIR, 'assets.js'), makeManifest(chunks));
  chunks.forEach(chunk => outputs.set(path.join(JS_DIR, chunk.file), chunk.text));
  return { sources, chunks, outputs };
}

function main() {
  const check = process.argv.includes('--check');
  const generated = generatedFiles();
  let stale = 0;
  generated.outputs.forEach((text, file) => {
    if (check) {
      if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== text) {
        console.error('STALE ' + path.relative(ROOT, file));
        stale++;
      }
    } else {
      fs.writeFileSync(file, text);
      console.log('生成 ' + path.relative(ROOT, file) + ' (' + Buffer.byteLength(text) + ' bytes)');
    }
  });
  if (check && stale) process.exitCode = 1;
  else if (check) console.log('音频生成物与源文件一致 ✓');
  else console.log('音频已拆分：42 SFX + 1 day + 1 night');
}

if (require.main === module) {
  try { main(); }
  catch (error) { console.error(error.message); process.exitCode = 1; }
}

module.exports = { generatedFiles, chunkHash };
